name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Download DLLs for Windows
      run: >
        C:\msys64\usr\bin\wget.exe https://github.com/webview/webview_csharp/raw/master/libs/webview.dll
        https://github.com/webview/webview_csharp/raw/master/libs/WebView2Loader.dll
      if: ${{ success() && matrix.os == 'windows-latest' }}

    - name: Install dependencies on Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends libwebkit2gtk-4.0-dev
      if: ${{ success() && matrix.os == 'ubuntu-latest' }}

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
#        if [ -f Gopkg.toml ]; then
#            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
#            dep ensure
#        fi

    - name: Build
      run: go build -ldflags="-s -w" -v .

    - name: Build Windows GUI binary
      run: go build -ldflags="-s -w -H windowsgui" -o modpack-cli.exe -v .
      if: ${{ success() && matrix.os == 'windows-latest' }}

    # - name: Test
    #   run: go test -v .
    
    - name: Upload a Build Artifact (Linux)
      uses: actions/upload-artifact@v2.1.4
      if: ${{ success() && matrix.os == 'ubuntu-latest' }}
      with:
        # Artifact name
        name: modpack-linux # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: modpack
        # The desired behavior if no files are found using the provided path.

    - name: Upload a Build Artifact (macOS)
      uses: actions/upload-artifact@v2.1.4
      if: ${{ success() && matrix.os == 'macos-latest' }}
      with:
        name: modpack-macos
        path: modpack

    - name: Upload a Build Artifact (Windows)
      uses: actions/upload-artifact@v2.1.4
      if: ${{ success() && matrix.os == 'windows-latest' }}
      with:
        name: modpack-windows
        path: |
          modpack.exe
          modpack-cli.exe
          webview.dll
          WebView2Loader.dll
