name: Go CI

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        cache: yarn
        cache-dependency-path: ui/yarn.lock

    - name: Set up Go 1.19
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19
        cache: true
      id: go

    - name: Download DLLs for Windows
      run: >
        C:\msys64\usr\bin\wget.exe https://github.com/webview/webview_csharp/raw/master/libs/webview.dll
        https://github.com/webview/webview_csharp/raw/master/libs/WebView2Loader.dll
      if: ${{ success() && matrix.os == 'windows-latest' }}

    - name: Install dependencies on Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends libwebkit2gtk-4.0-dev
      if: ${{ success() && matrix.os == 'ubuntu-18.04' }}

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        cd ui && yarn install --immutable && cd ..

    - name: Build
      run: cd ui && yarn build && cd .. && go build -ldflags="-s -w" -v .
      if: ${{ success() && matrix.os != 'windows-latest' }}

    - name: Build Windows CLI binary
      run: go build -tags clionly -ldflags="-s -w" -o modpack-cli.exe -v .
      if: ${{ success() && matrix.os == 'windows-latest' }}

    - name: Build Windows GUI binary
      run: cd ui && yarn build && cd .. && go build -ldflags="-s -w -H windowsgui" -v .
      if: ${{ success() && matrix.os == 'windows-latest' }}

    - name: Build Windows GUI launcher
      run: go build -tags launcher -ldflags="-s -w -H windowsgui" -o launcher.exe -v launcher.go
      if: ${{ success() && matrix.os == 'windows-latest' }}

    - name: Test
      run: go test -v .
    
    - name: Upload a Build Artifact (Linux)
      uses: actions/upload-artifact@v3
      if: ${{ success() && matrix.os == 'ubuntu-18.04' }}
      with:
        # Artifact name
        name: modpack-linux
        path: modpack

    - name: Upload a Build Artifact (macOS)
      uses: actions/upload-artifact@v3
      if: ${{ success() && matrix.os == 'macos-latest' }}
      with:
        name: modpack-macos
        path: modpack

    - name: Upload a Build Artifact (Windows)
      uses: actions/upload-artifact@v3
      if: ${{ success() && matrix.os == 'windows-latest' }}
      with:
        name: modpack-windows
        path: |
          modpack.exe
          modpack-cli.exe
          launcher.exe
          webview.dll
          WebView2Loader.dll
